## Docker Multistage construction

### DEV Environmental Science  ###
FROM node:14.18.2 AS nest-development

#  Navigate to the container working directory
WORKDIR /usr/src/app
#  Copy package.json
RUN npm install -g @nestjs/cli

COPY /nest-src/. .

# Install all dependencies
RUN npm install
# RUN npm run build
CMD [ "npm", "run", "start:dev"]

